chromosomes: ["chr13", "chr18", "chr21"]


threshold: 0.01
pathogenic: ["DelMis", "ClinVar"]


outdir: "out/"


files:
    ancestry: "files/barcode_study_ancestry.tsv"
    pop_count: "files/TCGA_ancestry_count.tsv"
    cancer_count: "files/TCGA_cancer_count.tsv"
    CPG_CPGlike_list: "files/CPG_PPI_input_merging_v2.tsv"

gene_subset: ["CPGs", "nonCPGs"]
