# chr: ["1", "2", "3"]
chr: ["4", "5"]
# chr: ["6", "7", "8", "9"]
# chr: ["10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "X"]



preheader: ['ID', 'FILTER']
infos: [0]
formats: ['GT', 'AD', 'DP', 'GQ', 'RD']